Current issue is an internal server error when executing the GetBookingItemsByDate endpoint
* error is  giving:
System.InvalidOperationException: The LINQ expression 'DbSet<BookingItemModel>()
    .Where(b => DateTime.Parse(b.DateTimeTaken).Date == __date_Date_0)' could not be translated. Additional information: Translation of method 'System.DateTime.Parse' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.